project:
  type: website
  output-dir: _site

website:
  title: "Student Mental Health Network"
  navbar:
    background: "#1C2944"
    foreground: white
    logo: logo-white.png
    logo-alt: "SMHN Logo"
  page-navigation: true
  search: true

format:
  html:
    theme: cosmo
    toc: true