project:
  type: website
  output-dir: .

website:
  title: "Student Mental Health Network"
  navbar:
    background: "#1C2944"
    foreground: white
    logo: logo-transparent-white-text.png
    logo-alt: "SMHN Logo"
    logo-href: "https://www.studentmentalhealthnetwork.ca"
  page-navigation: true
  search: true

format:
  html:
    theme: cosmo
    toc: true